### ISSUE TITLE
why not change color titr and description ?

### ISSUE THREAD

**Issue by mahdimortazavi** [ihsanbal/SlidingIntoView#1]
`  <com.ihsanbal.introview.IntroView
        android:id="@+id/intro.view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="right"
        app:paddingTextLeft="14dp"
        app:paddingTextRight="14dp"
        app:paddingTitleLeft="14dp"
        app:paddingTitleRight="14dp"
        app:paddingTitleTop="30dp"
        app:scaleType="centerCrop"
        app:scrollDelay="4000"
        app:scrollDuration="5"
        app:textColor="#2b2b2b"
        app:textSize="11sp"
        app:titleTextColor="#212121"
        app:titleTextSize="20sp" />`

![photo_2016-11-09_16-24-05](https://cloud.githubusercontent.com/assets/10667180/20138982/f3cc843e-a698-11e6-9244-af3df831740a.jpg)

**Comment by ihsanbal** [comment]
@mahdimortazavi fixed with [v1.0.1](https://github.com/ihsanbal/SlidingIntoView#how-to-use)
